### ISSUE TITLE
请添加一个在线地图的调用功能，谢谢

### ISSUE THREAD

**Issue by sasha6806** [daixianceng/yii2-echarts#1]
echarts现在不提供市县级矢量地图，官网建议用户改用百度在线地图。在线地图的调用需要注册echarts\extension\bmap.js文件，您的这个插件目前还不能注册bmap文件，劳驾您把它加进去 ，谢谢！
最好能增加一个dist的状态，以便可以选择是否加入bmap

**Comment by daixianceng** [comment]
已经支持，不过我并没有严格测试，你可以设置"dev-master"来安装使用这个功能，如果可以的话我会发布一个新版本，用法：`ECharts::$extensions = ['bmap'];`
